# Generated by Django 4.2.7 on 2023-11-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sensor1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sensor2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sensor3',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
